In [ ]:
# Youtube import files guide
# We don't have to upload file everytime
# https://www.youtube.com/watch?v=oqMImCeXi6o&ab_channel=TECHDOSE
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [ ]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [ ]:
train_downloaded = drive.CreateFile({'id':'19m6BU_Jenki8BZfdnQupFx5L9ytxythV'})
train_downloaded.GetContentFile('train.csv') 

test_downloaded = drive.CreateFile({'id':'1IUmFiVhWfGexxSs_UoOOSQn7fjuppOpT'})
test_downloaded.GetContentFile('test.csv') 

gender_submission_downloaded = drive.CreateFile({'id':'1v9E-zIqyOGNoEr69iigBK3P--y7Br-ke'})
gender_submission_downloaded.GetContentFile('gender_submission.csv') 

In [ ]:
import pandas as pd
train = pd.read_csv('train.csv') 
test = pd.read_csv('test.csv')
gender_submission = pd.read_csv('gender_submission.csv')

print(gender_submission)

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]


In [ ]:
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC

from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.feature_extraction import DictVectorizer

from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV, ParameterGrid

from sklearn import preprocessing, tree
from sklearn.model_selection import cross_val_score
from sklearn.impute import KNNImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import StackingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.impute import KNNImputer


import numpy as np


import warnings
warnings.filterwarnings("ignore")

In [ ]:
!pip3 install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip3 install tflearn 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import tensorflow as tf
import tflearn 


In [ ]:
df_train = pd.read_csv('./train.csv')
df_test = pd.read_csv('./test.csv')
df_train.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [ ]:

len(df_train), len(df_test)

(891, 418)

In [ ]:
df_train_copy = df_train.replace({'Sex': {'male': 0, 'female': 1}})
df_test_copy = df_test.replace({'Sex': {'male': 0, 'female': 1}})

In [ ]:
### Classifier based on gender alone

clf = MLPClassifier(hidden_layer_sizes=(10), max_iter=200,
                     solver='lbfgs', verbose=1,  random_state=42)  #sgd = Stochastic Gradient descent. Also, check 'lbfgs’, ‘adam’}
                                                                #Default activation is 'relu'
                                                                #Default n_iter_no_change=10
X_train = df_train_copy['Sex'].to_numpy().reshape(-1,1)
Y_train = df_train_copy['Survived']
clf.fit(X_train, Y_train)

print('Accuracy on training---')
y_pred_train=clf.predict(X_train)
print(accuracy_score(Y_train,y_pred_train))

Accuracy on training---
0.7867564534231201


## Manipulating Dataframe 
##### - Create Name Length column
##### - Filling in NaN Age values with average age
##### - Extract and make Cabin Deck column (i.e. A-G)

In [ ]:
### Create 'Name Length' column
df_train_copy['Name Length'] = [len(x) for x in df_train_copy['Name']]
df_test_copy['Name Length'] = [len(x) for x in df_test_copy['Name']]

In [ ]:
np.mean(df_train_copy['Age']), np.mean(df_test_copy['Age'])

(29.69911764705882, 30.272590361445783)

In [ ]:
df_train_copy

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    0  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1   
2                               Heikkinen, Miss. Laina    1  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1   
4                             Allen, Mr. William Henry    0  35.0      0   
..                                                 ...  ...   ...    ...   
886                              Montvila, Rev. Juozas    0  27.0      0   
887                       Graham, Miss. Margaret Edith    1  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"    1   NaN      1   
889                              Behr, Mr. Karl Howell    0  26.0      0   
890                                Dooley, Mr. Patrick    0  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Name Length  
0        0         A/5 21171   7.2500   NaN        S           23  
1        0          PC 17599  71.2833   C85        C           51  
2        0  STON/O2. 3101282   7.9250   NaN        S           22  
3        0            113803  53.1000  C123        S           44  
4        0            373450   8.0500   NaN        S           24  
..     ...               ...      ...   ...      ...          ...  
886      0            211536  13.0000   NaN        S           21  
887      0            112053  30.0000   B42        S           28  
888      2        W./C. 6607  23.4500   NaN        S           40  
889      0            111369  30.0000  C148        C           21  
890      0            370376   7.7500   NaN        Q           19  

[891 rows x 13 columns]

In [ ]:
df_test_copy

PassengerId  Pclass                                          Name  Sex  \
0            892       3                              Kelly, Mr. James    0   
1            893       3              Wilkes, Mrs. James (Ellen Needs)    1   
2            894       2                     Myles, Mr. Thomas Francis    0   
3            895       3                              Wirz, Mr. Albert    0   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    1   
..           ...     ...                                           ...  ...   
413         1305       3                            Spector, Mr. Woolf    0   
414         1306       1                  Oliva y Ocana, Dona. Fermina    1   
415         1307       3                  Saether, Mr. Simon Sivertsen    0   
416         1308       3                           Ware, Mr. Frederick    0   
417         1309       3                      Peter, Master. Michael J    0   

      Age  SibSp  Parch              Ticket      Fare Cabin Embarked  \
0    34.5      0      0              330911    7.8292   NaN        Q   
1    47.0      1      0              363272    7.0000   NaN        S   
2    62.0      0      0              240276    9.6875   NaN        Q   
3    27.0      0      0              315154    8.6625   NaN        S   
4    22.0      1      1             3101298   12.2875   NaN        S   
..    ...    ...    ...                 ...       ...   ...      ...   
413   NaN      0      0           A.5. 3236    8.0500   NaN        S   
414  39.0      0      0            PC 17758  108.9000  C105        C   
415  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S   
416   NaN      0      0              359309    8.0500   NaN        S   
417   NaN      1      1                2668   22.3583   NaN        C   

     Name Length  
0             16  
1             32  
2             25  
3             16  
4             44  
..           ...  
413           18  
414           28  
415           28  
416           19  
417           24  

[418 rows x 12 columns]

In [ ]:
### For age column, replace NaN values with average age

df_train_copy['Age'] = df_train_copy['Age'].fillna(np.mean(df_train_copy['Age']))
df_test_copy['Age'] = df_test_copy['Age'].fillna(np.mean(df_test_copy['Age']))


In [ ]:
# # Make groupby object

# groupby_age_train = df_train_copy.groupby(['Sex', 'Pclass'])['Age'].agg(['mean', 'median']).round(1)

# # Fill Nan values
# df_train_copy['Age'].mask((df_train_copy['Sex'] == 0) & (df_train_copy['Pclass'] == 1)  & (df_train_copy['Age'].isnull()), groupby_age_train['median'][0].iloc[0], inplace=True)
# df_train_copy['Age'].mask((df_train_copy['Sex'] == 0) & (df_train_copy['Pclass'] == 2)  & (df_train_copy['Age'].isnull()), groupby_age_train['median'][0].iloc[1], inplace=True)
# df_train_copy['Age'].mask((df_train_copy['Sex'] == 0) & (df_train_copy['Pclass'] == 3)  & (df_train_copy['Age'].isnull()), groupby_age_train['median'][0].iloc[2], inplace=True)

# df_train_copy['Age'].mask((df_train_copy['Sex'] == 1) & (df_train_copy['Pclass'] == 1)  & (df_train_copy['Age'].isnull()), groupby_age_train['median'][1].iloc[0], inplace=True)
# df_train_copy['Age'].mask((df_train_copy['Sex'] == 1) & (df_train_copy['Pclass'] == 2)  & (df_train_copy['Age'].isnull()), groupby_age_train['median'][1].iloc[1], inplace=True)
# df_train_copy['Age'].mask((df_train_copy['Sex'] == 1) & (df_train_copy['Pclass'] == 3)  & (df_train_copy['Age'].isnull()), groupby_age_train['median'][1].iloc[2], inplace=True)

# df_train_copy.head(8)

Current Accuracy on training---
0.8204264870931538

In [ ]:
### Get Cabin Deck from 'Cabin' Column (i.e. A-G)
# For cabin column, replace NaN Values with 0

df_train_copy['Cabin'] = df_train_copy['Cabin'].fillna(0)
df_test_copy['Cabin'] = df_test_copy['Cabin'].fillna(0)

# Use RegEx to extract 1st letter of Cabin Column entry to get Cabin deck

df_train_copy['Cabin Deck']=df_train_copy['Cabin'].str.extract(r'([A-Z])')
df_test_copy['Cabin Deck']=df_test_copy['Cabin'].str.extract(r'([A-Z])')

Current Accuracy on training---
0.8260381593714927

In [ ]:
### Extract Title from Name Column ('Mr, Mrs, Miss')

df_train_copy['Title']=df_train_copy['Name'].str.extract(r', (\w+).')
df_test_copy['Title']=df_test_copy['Name'].str.extract(r', (\w+).')

Current Accuracy on training---
0.8316498316498316

In [ ]:
### Fill Fare NaN Values
print(np.mean(df_train_copy['Fare']), np.median(df_train_copy['Fare']), np.mean(df_test_copy['Fare']), np.median(df_test_copy['Fare'].dropna()))
df_train_copy['Fare'] = df_train_copy['Fare'].fillna(np.mean(df_train_copy['Fare']))
df_test_copy['Fare'] = df_test_copy['Fare'].fillna(np.mean(df_test_copy['Fare'].dropna()))

32.204207968574636 14.4542 35.627188489208635 14.4542


In [ ]:
### OHE Columns where applicable

X_train_all = pd.get_dummies(df_train_copy[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked', 'Name Length', 'Cabin Deck', 'Title']])
X_test_all = pd.get_dummies(df_test_copy[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked', 'Name Length', 'Cabin Deck', 'Title']])

In [ ]:
clf2 = MLPClassifier(hidden_layer_sizes=(50,100,50), max_iter=900,
                     solver='lbfgs', verbose=1,  random_state=42)  #sgd = Stochastic Gradient descent. Also, check 'lbfgs’, ‘adam’}
                                                                #Default activation is 'relu'
                                                                #Default n_iter_no_change=10
clf2.fit(X_train_all, Y_train)

print('Accuracy on training---')
y_pred_train2=clf2.predict(X_train_all)
print(accuracy_score(Y_train,y_pred_train2))
scoresCLF2 = cross_val_score(clf2, X_train_all, Y_train, scoring='accuracy', cv=10)
np.mean(scoresCLF2), scoresCLF2

Accuracy on training---
0.9001122334455668


(0.7912609238451934,
 array([0.77777778, 0.75280899, 0.68539326, 0.80898876, 0.82022472,
        0.7752809 , 0.82022472, 0.7752809 , 0.83146067, 0.86516854]))

In [ ]:
X_test_all = X_test_all.reindex(labels=X_train_all.columns,axis=1).fillna(0)

In [ ]:
y_pred_test=clf2.predict(X_test_all)
#print(accuracy_score(Y_test,y_pred_test))
y_pred_test

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [ ]:
data = {'PassengerId': df_test['PassengerId'].values,
        'Survived': y_pred_test}
  
# Create DataFrame
predictions = pd.DataFrame(data)

In [ ]:
predictions.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1

In [ ]:
predictions.to_csv('predictions.csv', index=False)

Data Exploration

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df_train_copy.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name  Sex        Age  SibSp  \
0                            Braund, Mr. Owen Harris    0  22.000000      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.000000      1   
2                             Heikkinen, Miss. Laina    1  26.000000      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.000000      1   
4                           Allen, Mr. William Henry    0  35.000000      0   
5                                   Moran, Mr. James    0  29.699118      0   
6                            McCarthy, Mr. Timothy J    0  54.000000      0   
7                     Palsson, Master. Gosta Leonard    0   2.000000      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)    1  27.000000      0   
9                Nasser, Mrs. Nicholas (Adele Achem)    1  14.000000      1   

   Parch            Ticket     Fare Cabin Embarked  Name Length Cabin Deck  \
0      0         A/5 21171   7.2500     0        S           23        NaN   
1      0          PC 17599  71.2833   C85        C           51          C   
2      0  STON/O2. 3101282   7.9250     0        S           22        NaN   
3      0            113803  53.1000  C123        S           44          C   
4      0            373450   8.0500     0        S           24        NaN   
5      0            330877   8.4583     0        Q           16        NaN   
6      0             17463  51.8625   E46        S           23          E   
7      1            349909  21.0750     0        S           30        NaN   
8      2            347742  11.1333     0        S           49        NaN   
9      0            237736  30.0708     0        C           35        NaN   

    Title  
0      Mr  
1     Mrs  
2    Miss  
3     Mrs  
4      Mr  
5      Mr  
6      Mr  
7  Master  
8     Mrs  
9     Mrs

Using age mean 
Accuracy on training---
0.8271604938271605

Using age median 
Accuracy on training--- 0.8316498316498316
...same as just naively replacing age mean without consideration for sex and class...

In [ ]:
groupby_age_train = df_train_copy.groupby(['Sex', 'Pclass'])['Age'].agg(['mean', 'median']).round(1)

In [ ]:
groupby_age_train

mean  median
Sex Pclass              
0   1       39.3    36.0
    2       30.7    29.7
    3       27.4    29.7
1   1       34.1    32.5
    2       28.7    28.5
    3       24.1    28.0

In [ ]:
sum(df_train['Age'].isnull())

177

In [ ]:
df_train_copy.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   

             Ticket     Fare Cabin Embarked  Name Length Cabin Deck Title  
0         A/5 21171   7.2500     0        S           23        NaN    Mr  
1          PC 17599  71.2833   C85        C           51          C   Mrs  
2  STON/O2. 3101282   7.9250     0        S           22        NaN  Miss

In [ ]:
#same data cleaning and data engineering but using a decision tree classifier
vec = DictVectorizer()
le = preprocessing.LabelEncoder()
tree_data = X_train_all[['Pclass', 'Sex', 'Age']].to_dict('records')
tree_data = vec.fit_transform(tree_data).toarray()
X_tree = tree_data
y_tree = df_train_copy["Survived"]
tree_classify = tree.DecisionTreeClassifier(max_depth=10, random_state=42)
tree_classify.fit(X_tree, y_tree)
y_pred_tree = tree_classify.predict(X_tree)
sum(y_pred_tree == y_tree)/len(y_tree)

0.8585858585858586

In [ ]:
scoresTree = cross_val_score(tree_classify, X_tree, y_tree, scoring='accuracy', cv=10)
np.mean(scoresTree), scoresTree

(0.8103370786516854,
 array([0.8       , 0.82022472, 0.76404494, 0.85393258, 0.85393258,
        0.79775281, 0.78651685, 0.83146067, 0.82022472, 0.7752809 ]))

In [ ]:
#stacking ensemble method
estimators = [('rf', RandomForestClassifier(n_estimators=10, criterion="gini", random_state=42)), 
              ('nrn', MLPClassifier(hidden_layer_sizes=(10, 50, 10), solver='lbfgs', max_iter=400, verbose=1,  random_state=42)),
              ('kn', KNeighborsClassifier(n_neighbors=3))]
stacked = StackingClassifier(estimators, cv=5)
stacked.fit(X_tree, y_tree)
stacked.score(X_tree, y_tree)

0.8574635241301908

In [ ]:
#cross validation testing of ensemble method
cv = cross_val_score(stacked, X_tree, y_tree, scoring='accuracy', cv=10)
cv, np.mean(cv)

(array([0.81111111, 0.79775281, 0.74157303, 0.87640449, 0.85393258,
        0.79775281, 0.82022472, 0.78651685, 0.86516854, 0.80898876]),
 0.8159425717852683)

In [ ]:
# trying a neural network 


#replacing male and female to 1 or 0 
bin_df_train= df_train.replace('female', 1).replace('male', 0)
bin_df_test= df_test.replace('female', 1).replace('male', 0)

# Build neural network
neural_net = tflearn.input_data(shape= [None, 6])
neural_net = tflearn.fully_connected(neural_net, 64)
neural_net = tflearn.fully_connected(neural_net, 10, activation='softmax')

net = tflearn.regression(neural_net)

model = tflearn.DNN(net)
model.fit(bin_df_train, n_epoch=40, batch_size=32, show_metric=True)

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


TypeError: ignored

In [ ]:
data_enc = pd.get_dummies(df_train, columns = ['Sex'])
data_enc2= pd.get_dummies(df_train, columns = ['Sex'], drop_first=True)
data_enc2.head()

In [ ]:
female= len(data_enc[data_enc['Sex_male']==0])
male = len(data_enc[data_enc['Sex_male']==1])
print(pd.Series({'female': female, 'male': male}))


In [ ]:
y = data_enc2['Sex_male']
X = data_enc2.drop(['Sex_male', 'Name', 'Ticket', 'Cabin', 'Embarked'], axis=1).fillna(0)

X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.3,  
                                                    stratify=data_enc2['Sex_male'],
                                                    random_state=88,)
X_train.shape, X_test.shape

In [ ]:
negative = np.sum(y_train == 0)
positive = np.sum(y_train == 1)
print(pd.Series({'0': negative, '1': positive}))

In [ ]:
import matplotlib.pyplot as plt
from sklearn.tree import plot_tree
from sklearn.tree import DecisionTreeClassifier

dtc2 = DecisionTreeClassifier(min_samples_leaf=5, 
                              ccp_alpha=0.005,
                              random_state = 88)

dtc2 = dtc2.fit(X_train, y_train)

print('Node count =', dtc2.tree_.node_count)
plt.figure(figsize=(6,6))
plot_tree(dtc2, 
          feature_names=X_train.columns, 
          class_names=['0','1'], 
          filled=True,
          impurity=True,
          rounded=True,
          fontsize=12)  
plt.show() 

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

y_pred = dtc2.predict(X_test)
cm = confusion_matrix(y_test, y_pred)

print ("Confusion Matrix : \n", cm)
# print('Precision:',precision_score(y_test, y_pred))
# print('Recall:',recall_score(y_test, y_pred))

acc = (cm.ravel()[0]+cm.ravel()[3])/sum(cm.ravel())
TPR = cm.ravel()[3]/(cm.ravel()[3]+cm.ravel()[2])
FPR = cm.ravel()[1]/(cm.ravel()[1]+cm.ravel()[0])
print('Accuracy is: %.4f' %acc)
print('TPR is: %.4f' % TPR)
print('FPR is: %.4f' % FPR)

____________________________________________________
Different stacked ensemble method

In [ ]:
# Stacked Ensemble Attempt with Imputer
# df_train_jcopy = df_train_copy.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)
# df_test_jcopy = df_test_copy.drop(['Name', 'Ticket', 'Cabin'], axis=1)

# label = LabelEncoder()
# df_train_jcopy["Embarked"]= label.fit_transform(df_train_jcopy["Embarked"])
# df_test_jcopy["Embarked"]= label.transform(df_test_jcopy["Embarked"])

# print(len(df_test_jcopy))

418


In [ ]:
# df_train_jcopy.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  Name Length
0         0       3    0  22.0      1      0   7.2500         2           23
1         1       1    1  38.0      1      0  71.2833         0           51
2         1       3    1  26.0      0      0   7.9250         2           22
3         1       1    1  35.0      1      0  53.1000         2           44
4         0       3    0  35.0      0      0   8.0500         2           24

In [ ]:
# df_test_jcopy.head()

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  \
0          892       3    0  34.5      0      0   7.8292         1   
1          893       3    1  47.0      1      0   7.0000         2   
2          894       2    0  62.0      0      0   9.6875         1   
3          895       3    0  27.0      0      0   8.6625         2   
4          896       3    1  22.0      1      1  12.2875         2   

   Name Length  
0           16  
1           32  
2           25  
3           16  
4           44

In [ ]:
# we can use inputer to try and predict the Na values (sklearn) - do this for train and test set (Jovin)
# df_train_dict = df_train_jcopy.to_dict(orient='index').values()
# df_test_dict = df_test_jcopy.to_dict(orient='index').values()

# vect = DictVectorizer(sparse=False)
# encoded_train = vect.fit_transform(df_train_dict)
# encoded_test = vect.transform(df_test_dict)
# imputer = KNNImputer()
# X_raw_train = imputer.fit_transform(encoded_train)
# X_raw_test = imputer.transform(encoded_test)

In [ ]:
# X_raw_train

array([[22.    ,  2.    ,  7.25  , ...,  0.    ,  1.    ,  0.    ],
       [38.    ,  0.    , 71.2833, ...,  1.    ,  1.    ,  1.    ],
       [26.    ,  2.    ,  7.925 , ...,  1.    ,  0.    ,  1.    ],
       ...,
       [37.1   ,  2.    , 23.45  , ...,  1.    ,  1.    ,  0.    ],
       [26.    ,  0.    , 30.    , ...,  0.    ,  0.    ,  1.    ],
       [32.    ,  1.    ,  7.75  , ...,  0.    ,  0.    ,  0.    ]])

In [ ]:
# X_raw_test

array([[34.5   ,  1.    ,  7.8292, ...,  0.    ,  0.    ,  0.    ],
       [47.    ,  2.    ,  7.    , ...,  1.    ,  1.    ,  0.    ],
       [62.    ,  1.    ,  9.6875, ...,  0.    ,  0.    ,  0.    ],
       ...,
       [38.5   ,  2.    ,  7.25  , ...,  0.    ,  0.    ,  0.    ],
       [39.6   ,  2.    ,  8.05  , ...,  0.    ,  0.    ,  0.    ],
       [26.2   ,  0.    , 22.3583, ...,  0.    ,  1.    ,  0.    ]])

In [ ]:
#same data cleaning and data engineering but using a decision tree classifier
# vec = DictVectorizer()
# le = preprocessing.LabelEncoder()

# X_train_impute = pd.DataFrame(X_raw_train, columns=df_train_jcopy.columns)
# X_test_impute = pd.DataFrame(X_raw_test, columns=df_test_jcopy.columns)

# tree_data_train = X_train_impute[['Pclass', 'Sex', 'Age']].to_dict('records')
# tree_data_train = vec.fit_transform(tree_data_train).toarray()
# X_tree_train = tree_data_train
# y_tree_train = df_train_copy["Survived"]
# tree_classify_train = tree.DecisionTreeClassifier(max_depth=10, random_state=42)
# tree_classify_train.fit(X_tree_train, y_tree_train)
# y_pred_tree_train = tree_classify_train.predict(X_tree_train)
# sum(y_pred_tree_train == y_tree_train)/len(y_tree_train)

0.8585858585858586

In [ ]:
# tree_data_test = X_test_impute[['Pclass', 'Sex', 'Age']].to_dict('records')
# tree_data_test = vec.fit_transform(tree_data_test).toarray()
# X_tree_test = tree_data_test
# y_pred_tree_test = tree_classify_train.predict(X_tree_test)

# print(len(X_test_impute))

418


In [ ]:
# scoresTree = cross_val_score(tree_classify_train, X_tree_train, y_tree_train, scoring='accuracy', cv=10)
# np.mean(scoresTree), scoresTree

(0.6745942571785268,
 array([0.61111111, 0.64044944, 0.65168539, 0.69662921, 0.73033708,
        0.70786517, 0.66292135, 0.69662921, 0.6741573 , 0.6741573 ]))

In [ ]:
#stacking ensemble method
# estimators = [('rf', RandomForestClassifier(n_estimators=10, criterion="gini", random_state=42)), 
#               ('nrn', MLPClassifier(hidden_layer_sizes=(10, 50, 10), solver='lbfgs', max_iter=400, verbose=1,  random_state=42)),
#               ('kn', KNeighborsClassifier(n_neighbors=3))]
# stacked = StackingClassifier(estimators, cv=5)
# stacked.fit(X_tree_train, y_tree_train)
# stacked.score(X_tree_train, y_tree_train)

0.819304152637486

In [ ]:
# y_pred_ensemble = stacked.predict(X_tree_test)
# y_pred_ensemble
# print(len(y_pred_ensemble))

# df_test.shape

418


(418, 11)

In [ ]:
#cross validation testing of ensemble method
# cv = cross_val_score(stacked, X_tree_test, y_pred_ensemble, scoring='accuracy', cv=10)
# cv, np.mean(cv)

(array([0.85714286, 0.92857143, 0.92857143, 0.9047619 , 0.92857143,
        0.9047619 , 0.9047619 , 0.95238095, 0.90243902, 0.97560976]),
 0.9187572590011616)

In [ ]:
# submission_j = pd.DataFrame({
#         "PassengerId": df_test_jcopy["PassengerId"],
#         "Survived": y_pred_ensemble
#     })
# submission_j.to_csv('submission_jt.csv', index=False)